#+title: Antipatterns: Effectively working with non-Tech Teams as an ML Manager

* Summary
ML managers who work in Applied ML teams need to work with Business and Product people who are their stakeholders. While Product and Business managers are used to working with Engineering teams (backend, frontend etc.) some of them don't have experience working with ML teams. This can cause misunderstanding unless both sides take care to arrive at a "ways of working" model.
I provide some examples of antipatterns and how to identify them and then handle them.
* #1 "You promised to deliver this 4 days back"
** Identification
Deliverables are promised but don't get delivered on time. Product manager gets angry because they have to answer to  business. ML manager gets frustated because she knows that in ML work you can control the quality or the timeline of the output but it's generally difficult to control both.
** Handling
You are part of the problem. Educating the PM about the nature of ML work and committing for a Proof of Concept first helps. "Let's do the POC first. Then based on the learning I can commit on the MVP"
* #2 "Business EVP is saying our search page ranking is off. There are 2 products he should not be seeing"
** Identification
Business stakeholders need an explanation for something they feel is a discrepancy. PM is ruffled because she knows we should look at platform metrics but can't ignore individual user complaints as well. He asks "Do we have a bug?". You spend a lot of time in finding a bug because you dont' have a good systems' dashboard.
** Handling
You need 3 things here: a) Have dashboards that can quickly check that all pipelines and services are in order b)Provide users' events data to the PM so that they can convince themselves that the ranking is largely consistent with the users' events. Give them a self-serve debugging tool. Finally if there is not bug,  c)Educate the PM as well as the business leader that the ML algorithm is intended to maximize the experience for millions of users on the platform. It is possible that a specific user might not get a 100% accurate recommendation/ranking.

* #3 "As per design product x should be seen at position 6 in the first scroll  for  this type of user"

** Identification
A business manager who handles the category in which x falls is unhappy because he is not getting enough visibility. Product manager does not know how the algorithm works so he's unable to explain. ML manager tries to "fix" the issue but is often unsuccessful.

** Handling
The first action you should take in this case is to educate both PM and Business that an ML algorithm can't ensure that a particular product x is always ranked in a particular slot. This is not a bug but it's how ML works. While learning on a continual basis the model can end up changing scores. Some algorithms can have randomzied components so even if the input is the same the output can change slightly. If this sort of direct control is needed it's best to add an Engineering logic layer which overrides the ML ranking.
